<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="WS-Resource" targetNamespace="http://docs.oasis-open.org/wsrf/rw-2">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://docs.oasis-open.org/wsrf/rw-2">
            
  <xsd:import namespace="http://docs.oasis-open.org/wsrf/r-2" schemaLocation="r-2.xsd"/>
        
</xsd:schema>
  </types>
  <message name="ResourceUnavailableFault">
    <part element="wsrf-r:ResourceUnavailableFault" name="ResourceUnavailableFault">
    </part>
  </message>
  <message name="ResourceUnknownFault">
    <part element="wsrf-r:ResourceUnknownFault" name="ResourceUnknownFault">
    </part>
  </message>
</definitions>